name: Build Image using Containerfile, then push to Docker Hub and GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: visual-paradigm-ce
  IMAGE_TAGS: latest ${{ github.sha }}

jobs:
  build_and_push:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Buildah
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./Containerfile
  
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2.6
      id: push_ghcr
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry:  ghcr.io/${{ github.repository_owner }}
        username:  ${{ github.repository_owner }}
        password:  ${{ github.token }}
        extra-args: |
            --disable-content-trust
    - name: Push To Docker Hub
      uses: redhat-actions/push-to-registry@v2.6
      id: push_docker
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry:  docker.io/${{ github.repository_owner }}
        username:  ${{ github.repository_owner }}
        password:  ${{ secrets.DOCKER_HUB_SECRET }}
        extra-args: |
            --disable-content-trust
    - name: Docker Hub README & Description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user:  ${{ github.repository_owner }}
        pass:  ${{ secrets.DOCKER_HUB_SECRET }}
        slug: ${{ github.repository_owner }}/${{ steps.build_image.outputs.image }}
        description: true
    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push_ghcr.outputs) }}"
        echo "${{ toJSON(steps.push_docker.outputs) }}"
